name: MineMoney-Towny
main: com.kraken.minemoneytowny.MineMoneyTowny
depends: [MineMoney, Towny]
version: 0.1
api-version: 1.20
commands: 
     mmt:
        description: Info for the MineMoney-Towny plugin.
        usage: /<command>
     mmt buy:
        description: Buy bonus Towny blocks/plots.
        usage: /<command> <bonuses_to_buy>